openapi: 3.0.0
servers:
  - description: Surgical Process Monitoring Microservice
    url: http://localhost:<port>/api
info:
  description: This is the API of the Surgical Process Monitoring microservice within the Smart Operating Block project.
  version: 1.0.0
  title: Surgical Process Monitoring API
  contact:
    email: info@smartoperatingblock.com
  license:
    name: MIT License
    url: 'https://opensource.org/license/mit/'
